### ISSUE TITLE
Standard code style.

### ISSUE THREAD

**Issue by Noctifer-de-Mortem** [Noctifer-de-Mortem/nocs_cata_mod#2]
Most of this code is copy and paste from notepad, not notepad++, notepad. As a result, this has lead to code within the same file to have different or no style what-so-ever making it look very messy, I would like to have each file follow a style standard so that it is easier to read.

**Comment by ZhilkinSerg** [comment]
https://github.com/Noctifer-de-Mortem/nocs_cata_mod/pull/18

**Comment by Noctifer-de-Mortem** [comment]
Saw and merged.
