### ISSUE TITLE
Release v2.0 issue

### ISSUE THREAD

**Issue by ethanparkerr** [Noctifer-de-Mortem/nocs_cata_mod#22]
The provided file isn't up to date, for example it doesn't include those spelling fixes.

This link is up to date:

https://github.com/Noctifer-de-Mortem/nocs_cata_mod/archive/master.zip

**Comment by Noctifer-de-Mortem** [comment]
Thanks for the heads up! Will update the release with the correct file along with the onedrive link.

**Comment by Noctifer-de-Mortem** [comment]
Uploads completed.
