### ISSUE TITLE
Mapgen broken

### ISSUE THREAD

**Issue by Maddremor** [Noctifer-de-Mortem/nocs_cata_mod#25]
Latest experimental builds changed mapgen. Thus things are broke. Plausably something in the neighbourhood of [this](https://github.com/CleverRaven/Cataclysm-DDA/commit/d87f04fb77bff8b5cb2226d8fd9a609f254b8614).

**Comment by Noctifer-de-Mortem** [comment]
Thanks for the issue! It appears a change in that PR messed things up but it might be beyond rotation. Since its the weekend I should have a fix soon. Heres to hoping.
