### ISSUE TITLE
invalid overmap terrain ID

### ISSUE THREAD

**Issue by Maddremor** [Noctifer-de-Mortem/nocs_cata_mod#28]
Upon loading the playspace, the `error invalid overmap terrain ID "surv_camp"` is given along with correspondning error messages for every terrain ID. The game then crashes. The game does not crash if Cataclysm++ is not an active mod.

**Comment by Maddremor** [comment]
Errror message on crash:

```
---------------------------
MinGW Runtime Assertion
---------------------------
Assertion failed!

Program: D:\Program Files Installess\Games\Roguelike\Cataclysm\cdda\cataclysm-tiles.exe
File: src/overmap.cpp, Line 511

Expression: directional_peers.size() == om_direction::size
---------------------------
Abort   Retry   Ignore   
---------------------------

```

**Comment by Noctifer-de-Mortem** [comment]
Where did you donwload the mod?

**Comment by Maddremor** [comment]
Clone of this Github repo

**Comment by Noctifer-de-Mortem** [comment]
Let me test that again.

**Comment by Maddremor** [comment]
I'll check for weirdness on my end again.

**Comment by Maddremor** [comment]
Nope, still crashes with Cata++, but runs without.

**Comment by Maddremor** [comment]
Problem remains running Cata++ as only mod.

**Comment by Noctifer-de-Mortem** [comment]
Let me test on a newly installed game.

**Comment by Noctifer-de-Mortem** [comment]
Installed new game version 6296. Installed github repo clone of the mod and loaded a world with only it (and of course the core mod). Was able to generate new world and start world with no issues.

**Comment by Maddremor** [comment]
Huh. After a clean install, it works again for me. Must have borked the binaries or something.
