### ISSUE TITLE
Nothing broken, but changes to tailoring in experimental.

### ISSUE THREAD

**Issue by Maddremor** [Noctifer-de-Mortem/nocs_cata_mod#29]
Since [this](https://github.com/CleverRaven/Cataclysm-DDA/pull/20270) pull, crafting no longer uses charges from the sewing tool, but instead refers to `"using": [ [ "filament", 10 ] ]`. It would be nice if Cata++ could also use this convention.

**Comment by Noctifer-de-Mortem** [comment]
Let me take a look, from a simple skim it looks like changes to recipes might be enough.

**Comment by Noctifer-de-Mortem** [comment]
See #31.
