### ISSUE TITLE
The mod seems to be broken on the latest experimental build

### ISSUE THREAD

**Issue by Murumuru** [Noctifer-de-Mortem/nocs_cata_mod#30]
Once installed and enabled, the game does not progress further mapgen.

**Comment by Noctifer-de-Mortem** [comment]
No errors, just failed to load?

**Comment by Noctifer-de-Mortem** [comment]
Seems to be working fine on a fresh install of the game with no other mods. What is your list of mods for the current world?

**Comment by Murumuru** [comment]
I get endless "Finalization" stage on map generation with the mod enabled.
I had only this mod enabled.

**Comment by Noctifer-de-Mortem** [comment]
Try updating the game and download the latest version of the mod and see if it works. It has on my end while making the update.

**Comment by Murumuru** [comment]
After some more testing, I figured out it happens randomly for me, with increase in frequency if I have other mods enabled. 
I have no idea what causes it, might me non-default world settings or something. 
Haven't checked other mods, they might have the same issue.

**Comment by Noctifer-de-Mortem** [comment]
Maybe not world settings (those would spit errors) but settings like graphics and interface.

**Comment by Murumuru** [comment]
I do have non-default font with non-default font settings, but somehow I doubt it could be the issue. 
Just in case, I am using Curse version.
