### ISSUE TITLE
Allow to recharge batterie powered items with car batteries.

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [Noctifer-de-Mortem/nocs_cata_mod#32]
I'm aware that there's a mod that allows car batteries to be attached to some items, and that makes sense for electric stoves, forge, etc.

But when I want to recharge my torches, or small stoves that I keep with me, I can't recharge them via car batteries. That makes no sense to me. There should be some sort if item, thjat allows thjis.

**Comment by Noctifer-de-Mortem** [comment]
The mod that allows for using car battieries doesn't work for flashlights or stoves/hotplates? If nothing is hardcoded for that mod then it could be "fix" (overriden) to accept those items.

Let me take a look when I am able.

**Comment by Unrepentant-Atheist** [comment]
The point it I don't want a 50kg Head Torch straped on me.

**Comment by Noctifer-de-Mortem** [comment]
If its recharges with a battery then it would not weight more than it should, if it uses a car battery as a power source then there is no way around that.

**Comment by Unrepentant-Atheist** [comment]
Which is why I opened this issue, hopping that this expansion would add another craftable mod, that allows battery powered items to be recharged via car batteries.

**Comment by Noctifer-de-Mortem** [comment]
Since I have not done power mods for tools, first I have to find out if they are hardcoded, if they are then its a no go.

**Comment by Noctifer-de-Mortem** [comment]
`,
  {
    "id": "magazine_battery_mod",
    "copy-from": "mod_battery",
    "type": "TOOLMOD",
    "category": "spare_parts",
    "name": "battery compartment mod",
    "description": "A battery compartment mod that allows using high-density, rechargeable vehicle batteries in regular tools.",
    "color": "light_green",
    "acceptable_ammo": [ "battery" ],
    "magazine_adaptor": [ [ "battery", [ "small_storage_battery", "medium_storage_battery", "battery_motorbike", "battery_car" ] ] ]
  }`

Seems to it will require having the extra weight of the car battery. Can't do it any other way at the moment.
