### ISSUE TITLE
Solar stuff not working?

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [Noctifer-de-Mortem/nocs_cata_mod#34]
I'm trying to get all the great Solar X stuff to work, but to no avail. For the flashlight it says "Reload more batteries or put in the sun to charge." I droped it on the tile on a sunny day and waited 2-3 hours, nada. Nothing.

Same for Solar Battery Recharger. No idea how it works...

**Comment by Noctifer-de-Mortem** [comment]
You have to have it in you inventory to work. Those items use artifact properties to work so you have to have them in your inventory.

**Comment by Unrepentant-Atheist** [comment]
Oh....maybe update the desciption :). Obliged. Gonna test it. Just have it in my inventory? But the headtorch, can I have it equipped to recharge?

**Comment by Unrepentant-Atheist** [comment]
Maybe it's because I debbuged it in, but the Solar Recharger bugged out. It starts at (0) and goes  up, but when I unload it I get the "none" ammo/part type in my inventory. That's because I haven't put in batteries. I haven't tested it with properly crafted ones. Maybe disallow unloading the Recharger to (0) and at least must have (1) charge of battery all the time to solve this bug?

**Comment by Noctifer-de-Mortem** [comment]
Now that's a weird bug might have to prevent unloading and only allow to get the batteries to be haved when it is full via a crafting recipe.

**Comment by Unrepentant-Atheist** [comment]
Btw. same problem with the goo jerrycan. Unloading gives me "none" as ammo.

**Comment by Noctifer-de-Mortem** [comment]
Hmmm, might be an ammo problem then. If that is the case maybe the problem might be with the core game or maybe some definitions have changed.

**Comment by Noctifer-de-Mortem** [comment]
Sadly changes to how charges work made it so that "solar recharges" can no longer work. I had to remove such items. That renders this issue closed.

P.S: Stuff like the solar flashlight and solar fire starter still work and are not gone.
