### ISSUE TITLE
Make NPCs have custom weapons, armor and items.

### ISSUE THREAD

**Issue by Noctifer-de-Mortem** [Noctifer-de-Mortem/nocs_cata_mod#4]
Right now this mod's NPCs use standard classes which define their items. I would like for NPCs have their defined clothing and wield their own weapons like bio-weapon blade to wild wither the bionic blade or bionic sword.

**Comment by chaosvolt** [comment]
You can add overrides for wielded item, worn stuff, and misc. inventory contents. Defined in the JSONized class entries, and mostly just used by the bee NPC to spawn naked.

I intend to use it in Arcana to make arcanist NPCs, but not until I can get quests and such to work sanely. Plus if I had, say, blood mage NPCs, I'd want them to be hostile by default unless the player picked blood mage as their profession.

**Comment by Noctifer-de-Mortem** [comment]
Oh, is had not heard of this introduction to NPC classes of items. This should prove useful. 

As for NPCs not being hostile, I have that problem too where failed_bio_weapons are always hostile even if you pick the failed bio_weapon profession.

**Comment by chaosvolt** [comment]
Yeah, currently there's no way to mess with faction attitude using profession, trait, whatever. If I had that plus making your available responses in a conversation vary, I could make it so that hostile NPCs have nothing to say if you aren't the right sort of profession, but gain meaningful conversation if neutral.

**Comment by chaosvolt** [comment]
One step closer. When I get home later tonight I'll fiddle with the super soldier NPCs, I guess. They should be easier to figure out than the slave fighters, since they can be modeled a bit more like their player equivalents.

**Comment by Noctifer-de-Mortem** [comment]
Thanks to @chaosvolt and his recent PRs on NPCs, I believe all custom NPCs have their appropriate classes and custom classes their appropriate item. This issue is now done!

**Comment by Noctifer-de-Mortem** [comment]
Issue Closed by #51
