### ISSUE TITLE
goo jerrycan acting wierd 

### ISSUE THREAD

**Issue by MagicalCube** [Noctifer-de-Mortem/nocs_cata_mod#55]
i can't craft it only debug works i used to be able 2 craft it a few updates ago, also unloading it gives an error here is pic:
http://imgur.com/a/ckZDd
after unloading it i get an item called none which i can only get rid off by using debug

Also ari-gateau for mod

**Comment by MagicalCube** [comment]
sry my bad i am dumb

**Comment by Noctifer-de-Mortem** [comment]
#42 
I had to remove the item since changes to charge definitions of items changes and said items would no longer work. I am sorry if this was not communicated properly.
