### ISSUE TITLE
Fungaloids spawn infinitely on death

### ISSUE THREAD

**Issue by Sagan-Ro** [Noctifer-de-Mortem/nocs_cata_mod#61]
Awesome mod!  However, I have a game-breaking issue which has already cost me a save.

SUBJECT: When killed, Fungaloids split infinitely, or at least until my computer killed CDDA as "unresponsive".  I think the splitting may be a "feature" of Cataclysm++, since fungal splitting does not occur if I use the Chemical Thrower with Sprayable Fungicide.

ISSUE: After noticing the unlimited splitting, I became very careful.  However, in a town I parked my laser-turret-equipped deathbike to loot some stores.  As I returned from across town, the game suddenly started hiccuping: a Fungal supersoldier had spawned near my bike, and been killed, spawning a Fungaloid.  Laserfire had ignited the fungal patches under the first Fungaloid, killing it and causing more Fungaloids and fungal patches to spawn, which were ALSO ignited.  By the time I moved about 50 spaces (from edge-of-sight to within same-screen distance of my vehicle) I had over 500 Fungaloids in sight, with an unknown number hidden by buildings.  Three more moves and the program froze permanently.

I had saved while across town after finding some nice loot.  I had to abandon my vehicle and Debug Teleport away from the city.  I could not return to that city because the splitting kept crashing the game when I got near.

PROPOSED SOLUTIONS: There are several.

1.  Simply remove Fungaloids splitting upon death.  Obvious and easy, especially if this is a bug.  However, if splitting is a "feature", then...
2.  Limit ABSOLUTE number of splits.  Example: A found Fungaloid is killed.  It can split into "immature" Fungaloids, but those CAN'T split since they aren't "mature enough".  This way you can keep splitting, but the player can still brute-force-kill Fungaloids if they are surprised without access to anti-fungal chemicals.  Fire is really the only option available to players if they *have* to fight Fungal Infestations (which splitting makes a certainty!) without anti-fungal chemicals, which leads me to...
3.  Possibly stop spawned Fungaloids from creating flammable Fungal Patches underneath them.  This isn't necessary if you implement Solution 1 or 2, but it is ESSENTIAL if you don't do anything else!  Remember, I lost a very advanced save because a fire *I didn't start* caused an infinite cycle: Fire kills Fungaloid, Fungaloid splits, new Fungaloids create Fungal Patches, Fire ignite Fungal Patches, Fire kills new Fungaloids, etc.  Remember, I didn't have even have time to move into range to even BEGIN to put out the fire before it had engulfed 5 houses and spawned 500+ Fungaloids.  And you can't stop a fire like that, when it's growing 3 square per turn PER FUNGALOID (as each spawns new Fungal Patches), and a fire extinguisher allows 1 square of fire extinguished per turn.

Thank you for your time and a really great mod!

**Comment by Noctifer-de-Mortem** [comment]
This sounds like a serious issue. I'll probaly implement solution 2 then. May I know the specific monster you killed? I doubt it's the only one.

**Comment by Sagan-Ro** [comment]
It was late-game, I had turned up monster evolution to maximum and gifted myself some of the new equipment in Cataclysm++.  I had killed a **Fungal Bio-Weapon** creature a previous time, and it spawned a Fungaloid on death.  The type of Fungaloid spawned is the adult type that moves around, and in vanilla spawns spore clouds on death.  That's why I thought maybe this was a bug: perhaps some coding got switched so Fungaloids spawn themselves instead of the spore clouds.

Anyway, that first Fungal Bio-Weapon (I use tiles, but it's symbolized by an "F" in Chesthole-iso tiles instead of Z for normal Bio-Weapon enemies) nearly broke my game, but I ALT-F4'd out and restored an earlier save.  That's when I thought "maybe this is supposed to be a feature" and started trying out the Chemical Thrower (which keeps Fungaloids from splitting for some reason.)

So several in-game days later... I am guessing that while I was away looting on the other side of town, another Fungal Bio-Weapon spawned near my vehicle.  I leave my turrets on auto to keep my vehicle from getting destroyed by zombies, you see.  The turrets must have destroyed the Fungal Bio-Weapon, which spawned a Fungaloid, which was killed and started splitting.  Meanwhile the lasers ignited the fungal patches getting created, which kill/split all new Fungaloids ad nauseam.  Like I said, I had to teleport out and never approach the city again, because the game crashed whenever that mess of Fungaloids and fire entered my player's reality bubble.

The only way I got around it was to delete all the map files from my save folder, thus resetting the world.  A real bummer, though, since I only got to keep what I was carrying at the time (my vehicle was my stash).

Also, CDDA has been kind of wonky, so see if you can recreate this error on your end.  I was using CDDA experimental 6685 (tiles) 64 bit on Windows 10, with Cataclysm++ from 8/5/2017.  Fungaloids only started doing this splitting when I used my old save and created a new world with your mod, so it's either your mod or my save was screwed up.  Unfortunately I don't have the save file to send you: I deleted it and decided to cheat-start afresh.

**Comment by Noctifer-de-Mortem** [comment]
I'll try to recreate it and if it is an issue, I will change the death function since bugs aren't worth it.

**Comment by Sagan-Ro** [comment]
UPDATE: I redownloaded Cataclysm++ directly from here (Github) instead of from Onedrive, and cheat-started a new game from scratch.  I just killed a Fungal Bio-Weapon with a Laser Gatling CBM and no Fungaloids are pouring forth.  Very happy with that, but also wondering what could have caused the problem to start with...?

Oh well, I'll take fewer bugs any day.  Woohoo!

**Comment by Noctifer-de-Mortem** [comment]
Sorry to not have updated by I did test it and found no issues myself. Might of been either a glitch with the game or a mod conflict of some sort. Glad to hear it's working. Will close the issue on that note but if it happens again, feel free to comment her and I'll reopen it.

**Comment by Sagan-Ro** [comment]
Oh, boy... it's back.  On world generation I accidentally enabled the "No Triffids" mod, but disabling it makes the bug reappear.  Recreating the bug is simple: use the debug menu to spawn "fungaloid", kill it, and just see what happens.

Crap crap crap...

**Comment by Noctifer-de-Mortem** [comment]
Sorry for the late response but it took a while to test this and come to the conclusion I did. The fungaloids only spawned as they did since you had turned evolution to max. The mod makes spores spawn from fungal failed bio-weapons but with evolution set to max, the spores clouds immediately become adult versions. The splitting illusion is created since the adults create more spore clouds and they in turn become adults as well really quickly. This creates a self feeding cycle creating the problem you described.

This will happen with any fungus creature that creates spore clouds, not just the ones in the mod, as long as monster evolution is so high. So my suggestion is to either turn the monster evolution down or stay away from the fungus.
