### ISSUE TITLE
Patch request!

### ISSUE THREAD

**Issue by MrLabRat** [Noctifer-de-Mortem/nocs_cata_mod#67]
Could you update this to the latest experimental version? After CDDA patch #7072 it throws up some bionics errors.

Thanks!

**Comment by MrLabRat** [comment]
#68 fixes this!

**Comment by chaosvolt** [comment]
Closure reason? Screenshot of error?

**Comment by MrLabRat** [comment]
Sorry, I mistakenly closed it! Thanks for fixing it up!
